name: CMake

on:
  push:
    branches:
      - main

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
      # 1. Check out the code
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Configure CMake for Windows with Ninja, others with default
      - name: Configure CMake
        run: cmake -B build -S . -DCMAKE_BUILD_TYPE=Release
      
      # 3. Build project
      - name: Build project
        run: cmake --build build --config Release


      # 4. List the build directory (for debugging)
      - name: List build directory (debug)
        if: ${{ runner.os != 'macOS' }}
        run: dir build

      # 5. Upload build artifacts (adjusting the paths)
      - name: Upload build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: Build-${{ matrix.os }}
          path: |
            build/Release/Server
            build/Release/Client