name: CMake

on:
  push:
    branches:
      - main

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      #if os is windows, we don't want to build with VS so we install ninja ( there may be another way of doing things but we don't know)
      - name: Install Ninja
        if: runner.os == 'Windows'
        run: choco install ninja

      - name: Configure CMake with Ninja
        if: runner.os == 'Windows'
        run: cmake -G Ninja -B build -S .


      - name: Configure CMake
        if: runner.os != 'Windows'
        run: cmake -B build -S . -DCMAKE_BUILD_TYPE=Release


      - name: Build project
        run: cmake --build build --config Release

      - name: Upload build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: Build-${{ matrix.os }}
          path: build